### ISSUE TITLE
Option to display text on the right side

### ISSUE THREAD

**Issue by not-nef** [Moosems/TkLineNums#1]
I have already tried implementing this but i couldnt get the text to line up properely like this:

![image](https://user-images.githubusercontent.com/83908932/193064414-ca3a4e6b-d271-4883-a74d-f090c9913982.png)

Would you look into it please? Thanks! :D

**Comment by Moosems** [comment]
I'll look into it. To my current knowledge it defaults to the right with a bit of space from the sides

**Comment by Moosems** [comment]
Oops, just realized it meant right, not left 😆

**Comment by Moosems** [comment]
Fixed in pypi release 1.5

**Comment by not-nef** [comment]
Great thank you!
