### ISSUE TITLE
error in redraw function

### ISSUE THREAD

**Issue by lazeit** [Moosems/TkLineNums#19]
There is an error in the redraw function when there are more that 1000 lines:

```
def resize(self) -> None:
        """Resizes the widget to fit the text widget"""

        # Get amount of lines in the text widget
        end = self.textwidget.index("end").split(".")[0]

        # Set the width of the widget to the required width to display the biggest line number
        self.config(width=Font(font=(temp_font := self.textwidget.cget("font"))).measure(" 1234 ")) if int(
            end
        ) <= 1000 else self.config(width=temp_font.measure(f" {end} "))
```

Namely, temp_font will be undefined if int(end) > 1000. The fix looks pretty simple in that := can be replaced with a normal assignment operator of temp_font prior to calling self.config.

I would be happy to make a PR.

**Comment by Moosems** [comment]
Yes, that does seem to be an issue. There's currently a lot of changes on a particular branch so make a PR for that one. Also, if you would be open to help with the bugs appearing on that PR, that would really help push through the next update. Help is really needed as I can't figure it out for the life of me.

**Comment by Moosems** [comment]
`click_drag_bugs` is the branch, the other needs to be deleted.

**Comment by lazeit** [comment]
I noticed you already fix it in your pending changes for the click_drag_bugs branch.

**Comment by Moosems** [comment]
Dude you are a lifesaver. I spent more than 100 hours of my life confused how to fix those bugs so what you did means so much to me. Thank you so so much for your help.

**Comment by lazeit** [comment]
Of course! Glad I could help.
