### ISSUE TITLE
Combining with tkscrollbar doesn't work

### ISSUE THREAD

**Issue by AlexMartin17** [Moosems/TkLineNums#28]
Hi,

If you want to use it alongside tk.Scrollbar, I can't seem to find a way to tie it together, both scrolls work but not simultaneously.
Any ideas?

Thanks

**Comment by Moosems** [comment]
Im not quite sure I understand what you're trying to do here. Could you provide a small example of what you're trying to accomplish?

**Comment by AlexMartin17** [comment]
Hi

I've modified your example code to include tk scrollbar.
As you can see your scrolling doesn't scroll the scrollbar or vice versa.
The line nums aren't even drawn at first.

`import tkinter
from tkinter import Text, Tk
from tkinter.ttk import Style

from tklinenums import TkLineNumbers
root = Tk()

text = Text(root)
text.pack(side="right")

for i in range(50):
    text.insert("end", f"Line {i+1}\n")

linenums = TkLineNumbers(root, text, justify="center", colors=("#2197db", "#ffffff"))
linenums.pack(fill="y", side="left")

scroll = tkinter.Scrollbar()
scroll.pack(side="right", fill="y")

text.config(yscrollcommand=scroll.set)
scroll.config(command=text.yview)
text.bind("<<Modified>>", lambda event: root.after_idle(linenums.redraw), add=True)

root.mainloop()`

**Comment by Moosems** [comment]
Please see #16 :).

**Comment by Moosems** [comment]
I'll get a fixed example to you later :).

**Comment by Moosems** [comment]
Essentially you need to bind the yscrollcommand to a function that sets both simultaneously.
