### ISSUE TITLE
Adding tilde characters

### ISSUE THREAD

**Issue by lorenzolpandolfo** [Moosems/TkLineNums#29]
Hello, @Moosems !
First of all, I would like to thank you and all contributors for this amazing repository that's making my python text editor, Pytext, become true.
I'm opening this issue to discuss about a contribution to TkLineNums, to add tilde chars.

If you don't know what a tilde char is, I will show you an example with Vim:
![intro-vim-unix-text-editor-every-hacker-should-be-familiar-with w1456](https://github.com/Moosems/TkLineNums/assets/133379234/3ecbdc45-eca9-4c67-b2e0-c7b24901a956)
The "~" chars are tilde chars. They represent non-lines in the line counter. In the current TkLineNums, tilde chars are not customizable and, if a line index is not existent, it is just ignored.

I changed your code so user can add a custom tilde char to its TkLineNums instance.

Example in my current code:
`self.line_counter = TkLineNumbers(master, self, justify="right", colors=("#e3ba68", "#1D1E1E"),tilde="~", bd=0)`
![image](https://github.com/Moosems/TkLineNums/assets/133379234/9c52fb38-db0f-4e0b-b260-d78673cab592)

If user doesn't provide a tilde parameter, It will be None. In this case, TkLineNums will work normally, so projects that already use TkLineNums won't break.
```
    def __init__(
        self: TkLineNumbers,
        master: Misc,
        textwidget: Text,
        justify: str = "left",
        # None means take colors from text widget (default).
        # Otherwise it is a function that takes no arguments and returns (fg, bg) tuple.
        colors: Callable[[], tuple[str, str]] | tuple[str, str] | None = None,
        tilde: str | None = None,
        *args,
        **kwargs,
    ) -> None:
```
I hope you like my idea and my contribution is already done, It just needs to pull-request. Please, tell my what do you think about this new TkLineNums functionality.
Best regards!

**Comment by Moosems** [comment]
Hey @lorenzolpandolfo! I love the idea, I'll try and add it sometime later today or tomorrow. If I don't have a PR made with you pinged, just remind me and I'll get right to it!

**Comment by lorenzolpandolfo** [comment]
@Moosems Im happy that you liked it!
I'm updating my fork with bug fixes with tilde chars. Then, when It's done, I will pull request it.
Please, test it after accepting so we can make it run flawlessly. =)

**Comment by Moosems** [comment]
Thank you for the PR! I'm having a few issues and don't have the time to fix them at this moment but will make sure to take a look later today. If you could fix as much as you can in the meantime that'd be greatly appreciated!

**Comment by lorenzolpandolfo** [comment]
> Thank you for the PR! I'm having a few issues and don't have the time to fix them at this moment but will make sure to take a look later today. If you could fix as much as you can in the meantime that'd be greatly appreciated!

For sure! I will try my best to make this work perfectly. Also, I will change your observations in my code.
