### ISSUE TITLE
Mouse Scroll `sel`

### ISSUE THREAD

**Issue by Moosems** [Moosems/TkLineNums#6]
Add sel tag if the mouse is down in case it's not moving while scrolling

**Comment by Moosems** [comment]
`"<Button-1>"` and `"<MouseWheel">` can not be bound together from what I'm finding, if a binding can be found then this would become a whole lot easier.

**Comment by Moosems** [comment]
May not even be possible. Can't be done in VS Code, Chrome, or the `Text` widget. 

https://user-images.githubusercontent.com/95927277/233141898-ddabe9d3-4cf9-48db-927b-7fda23ec71a6.mov

**Comment by Moosems** [comment]
I don't think it's even possible to detect if the mouse is down when scrolling so I'm going to close this issue unless someone has an epiphany.

**Comment by rdbende** [comment]
> I don't think it's even possible to detect if the mouse is down when scrolling so I'm going to close this issue unless someone has an epiphany.

`<MouseWheel>` and then check `event.state`?

**Comment by Moosems** [comment]
Could you make a test? I tried this once and didn't get much but maybe I was doing it wrong.

**Comment by rdbende** [comment]
```py
import tkinter

root = tkinter.Tk()


def spam(event):
    # Now this only works when no other modifier key is pressed while scrolling
    # To filter out those you'd need some more logic
    # https://github.com/python/cpython/blob/3205d1fbbbfcf613b74d236be9db7a8225f452ea/Lib/tkinter/__init__.py#L250-L255
    print("Button 1 pressed:", event.state == 256)


root.bind("<Button-4>", spam)
root.bind("<Button-5>", spam)
root.bind("<MouseWheel>", spam)

root.mainloop()
```

**Comment by Moosems** [comment]
It always comes back as `False` when I test it :(

**Comment by rdbende** [comment]
Then it might be something mac-specific

**Comment by Moosems** [comment]
Possibly. I can't find a single application that can do it.
